name: proddemo123
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://37d0-2600-1700-550-7950-9819-d1b-be15-4f25.ngrok-free.app
          tlsSkipVerify: true
          method: jwt
          path: jwt_gha-wf
          role: jwt_gha-wf_role
          exportToken: true
          exportEnv: true
          secrets: |
            gha_wf/data/repo:BalaGanaparthi/GHActions:ref:refs/heads/main/jwt-github-actions-vault-secrets ** | MYAPP_ ;
      - name: Step following 'Import Secrets'
        run: |
          $APPSECRET = "${{ env.APPSECRET }}"
          echo "Stored Output: $APPSECRET"
