name: proddemo123
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Troubleshooting_1
        run: |
            curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
            jq "{ jwt: .value, role: \"jwt_gha-wf_role\" }" > ./token.json
            echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN = [$ACTIONS_ID_TOKEN_REQUEST_TOKEN] and ACTIONS_ID_TOKEN_REQUEST_URL = [$ACTIONS_ID_TOKEN_REQUEST_URL]"
            echo 'GitHub Actions Token Claims'
            cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq
            cat ./token.json
            curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" --data @token.json https://reqbin.netlify.app/.netlify/functions/reqbin
            echo 'Vault Login Response'
            curl -sSLf -X POST -H "Content-Type: application/json" -H "X-Vault-Namespace: admin" --data @token.json https://37d0-2600-1700-550-7950-9819-d1b-be15-4f25.ngrok-free.app/v1/auth/jwt_gha-wf/login
            # Remove the token file when we're done (if we don't fail )
            rm ./token.json
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://37d0-2600-1700-550-7950-9819-d1b-be15-4f25.ngrok-free.app
          path: jwt_gha-wf_g
          role: jwt_gha-wf_role_g
          method: jwt
          exportToken: true
          exportEnv: true
          secrets: |
            gha_wf_g/data/repo:GaneshP1234/myprodproject:ref:refs/heads/main/proddemo123 ** | MYAPP_ ;
      - name: Step following 'Import Secrets'
        run: |
          $MYAPP_ = "${{ env.MYAPP_ }}"
          echo "Stored Output: $MYAPP_"
