name: proddemo
# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            prod/data/apps_secret app_secret1 | APPSECRET ;
      - name: Step following 'Import Secrets'
        run: |
          #$APPSECRET = "${{ steps.import-secrets.outputs.app_secret1 }}"
          $APPSECRET = "${{ env.APPSECRET }}"
          echo "Stored Output: $APPSECRET"
          #echo '${{ toJson(steps.import-secrets.outputs) }}'
          #echo "${{ toJson(steps.import-secrets.outputs) }}"
          echo '${{ toJson(steps.import-secrets.outputs) }}' > secrets.json
          #cat secrets.json
      - name: Export JSON File
        run: |
          # Example: Move the file to another location or make it available for download.
          mv secrets.json C:\HashiCorp
